import { QueryRunner } from 'typeorm';

export class init1667486107845 {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // language=PostgreSQL
    await queryRunner.query(`
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';

create table public.tournament
(
    id             integer generated by default as identity
        constraint tournament_id
            primary key,
    name           varchar(100)              not null
);
`);
  }
}
